// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://negybijotwasjqxkcosx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lZ3liaWpvdHdhc2pxeGtjb3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDQ0NTIsImV4cCI6MjA2NTE4MDQ1Mn0.SsEk_wlmy9AHFDLuCJGzFnph3GVE7ySgDI_aApQAigQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);